import numpy as np
import matplotlib.pyplot as plt
import os


# --------------------------------------------------
# Robot parameters
# --------------------------------------------------

L1 = 0.25
L2 = 0.30
L3 = 0.20


# --------------------------------------------------
# Forward kinematics
# --------------------------------------------------

def forward_kinematics(q):
    q1, q2, q3 = q

    x = (
        L1 * np.cos(q1)
        + L2 * np.cos(q1 + q2)
        + L3 * np.cos(q1 + q2 + q3)
    )

    y = (
        L1 * np.sin(q1)
        + L2 * np.sin(q1 + q2)
        + L3 * np.sin(q1 + q2 + q3)
    )

    return np.array([x, y])


# --------------------------------------------------
# Analytical Jacobian
# --------------------------------------------------

def jacobian(q):
    q1, q2, q3 = q

    dx_dq1 = (
        -L1 * np.sin(q1)
        - L2 * np.sin(q1 + q2)
        - L3 * np.sin(q1 + q2 + q3)
    )

    dx_dq2 = (
        -L2 * np.sin(q1 + q2)
        - L3 * np.sin(q1 + q2 + q3)
    )

    dx_dq3 = -L3 * np.sin(q1 + q2 + q3)

    dy_dq1 = (
        L1 * np.cos(q1)
        + L2 * np.cos(q1 + q2)
        + L3 * np.cos(q1 + q2 + q3)
    )

    dy_dq2 = (
        L2 * np.cos(q1 + q2)
        + L3 * np.cos(q1 + q2 + q3)
    )

    dy_dq3 = L3 * np.cos(q1 + q2 + q3)

    return np.array([
        [dx_dq1, dx_dq2, dx_dq3],
        [dy_dq1, dy_dq2, dy_dq3]
    ])


# --------------------------------------------------
# Numerical inverse kinematics
# --------------------------------------------------

def inverse_kinematics(target, q_initial, tolerance=1e-6, max_iterations=100):

    q = q_initial.copy()

    # REAL solver history
    position_history = [forward_kinematics(q).copy()]
    error_history = [
        np.linalg.norm(target - position_history[-1])
    ]

    for iteration in range(max_iterations):

        current_position = forward_kinematics(q)
        error = target - current_position
        error_norm = np.linalg.norm(error)

        print(
            f"Iteration {iteration:02d} | "
            f"Position = {current_position} | "
            f"Error = {error_norm:.10f} m"
        )

        if error_norm < tolerance:
            break

        J = jacobian(q)

        # Moore-Penrose pseudoinverse IK update
        delta_q = np.linalg.pinv(J) @ error

        q = q + delta_q

        # Save ACTUAL position produced by this solver step
        new_position = forward_kinematics(q)

        position_history.append(new_position.copy())
        error_history.append(
            np.linalg.norm(target - new_position)
        )

    return (
        q,
        np.array(position_history),
        np.array(error_history)
    )


# --------------------------------------------------
# Robot joint positions for visualization
# --------------------------------------------------

def get_joint_positions(q):

    q1, q2, q3 = q

    p0 = np.array([0.0, 0.0])

    p1 = np.array([
        L1 * np.cos(q1),
        L1 * np.sin(q1)
    ])

    p2 = p1 + np.array([
        L2 * np.cos(q1 + q2),
        L2 * np.sin(q1 + q2)
    ])

    p3 = p2 + np.array([
        L3 * np.cos(q1 + q2 + q3),
        L3 * np.sin(q1 + q2 + q3)
    ])

    return np.array([p0, p1, p2, p3])


# --------------------------------------------------
# IK visualization
# --------------------------------------------------

def plot_ik(q_initial, q_solution, target, position_history):

    initial_points = get_joint_positions(q_initial)
    solution_points = get_joint_positions(q_solution)

    plt.figure(figsize=(9, 9))

    # Initial robot
    plt.plot(
        initial_points[:, 0],
        initial_points[:, 1],
        "o--",
        linewidth=2,
        label="Initial Configuration"
    )

    # Final IK solution
    plt.plot(
        solution_points[:, 0],
        solution_points[:, 1],
        "o-",
        linewidth=3,
        label="IK Solution"
    )

    # REAL end-effector positions generated by IK iterations
    plt.plot(
        position_history[:, 0],
        position_history[:, 1],
        "o:",
        linewidth=2,
        markersize=6,
        label="End-Effector IK Iterations"
    )

    # Number each solver iteration
    for i, position in enumerate(position_history):
        plt.annotate(
            str(i),
            (position[0], position[1]),
            xytext=(6, 6),
            textcoords="offset points"
        )

    # Target
    plt.scatter(
        target[0],
        target[1],
        marker="x",
        s=160,
        linewidths=3,
        label="Target"
    )

    plt.xlabel("X Position [m]")
    plt.ylabel("Y Position [m]")
    plt.title(
        "3-DOF Planar Robot - Numerical Inverse Kinematics"
    )

    plt.axis("equal")
    plt.grid(True)
    plt.legend()

    os.makedirs("results", exist_ok=True)

    output_path = "results/inverse_kinematics_iterations.png"

    plt.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()

    print("\nVisualization saved to:", output_path)


# --------------------------------------------------
# Main
# --------------------------------------------------

if __name__ == "__main__":

    target = np.array([0.40, 0.45])

    q_initial = np.deg2rad([
        10.0,
        20.0,
        10.0
    ])

    q_solution, position_history, error_history = inverse_kinematics(
        target,
        q_initial
    )

    final_position = forward_kinematics(q_solution)
    final_error = np.linalg.norm(
        target - final_position
    )

    print("\n--------------------------------------")
    print("Target:", target)
    print(
        "Solved joint angles [deg]:",
        np.rad2deg(q_solution)
    )
    print("Final position:", final_position)
    print("Final error:", final_error)
    print("IK updates:", len(position_history) - 1)
    print("--------------------------------------")

    plot_ik(
        q_initial,
        q_solution,
        target,
        position_history
    )
